<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class KegiatanBobotSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $bobotData = [];

        // ===== KEGIATAN WAJIB INSTITUSI (ID_KEGIATAN_JENIS = 1, IS_HAVE_TINGKAT = false) =====
        // Hanya Peserta dan Panitia (tidak ada tingkat)

        // Peserta (ID_KEGIATAN_PRESTASI = 9)
        $bobotData[] = [
            'ID_KEGIATAN_JENIS' => 1,
            'ID_KEGIATAN_TINGKAT' => null,
            'ID_KEGIATAN_PRESTASI' => 9,
            'ID_KEGIATAN_DOKUMEN_TYPE' => 1,
            'POINT_KEGIATAN_BOBOT' => 10,
        ];

        // Panitia (ID_KEGIATAN_PRESTASI = 11)
        $bobotData[] = [
            'ID_KEGIATAN_JENIS' => 1,
            'ID_KEGIATAN_TINGKAT' => null,
            'ID_KEGIATAN_PRESTASI' => 11,
            'ID_KEGIATAN_DOKUMEN_TYPE' => 3,
            'POINT_KEGIATAN_BOBOT' => 15,
        ];

        // ===== KEGIATAN PILIHAN: BIDANG PENALARAN DAN KEILMUAN (ID_KEGIATAN_JENIS = 2, IS_HAVE_TINGKAT = true) =====

        // Juara 1 (ID_KEGIATAN_PRESTASI = 1)
        // Tingkat Internasional (ID = 1)
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 2, 'ID_KEGIATAN_TINGKAT' => 1, 'ID_KEGIATAN_PRESTASI' => 1, 'ID_KEGIATAN_DOKUMEN_TYPE' => 2, 'POINT_KEGIATAN_BOBOT' => 100];
        // Tingkat Nasional (ID = 2)
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 2, 'ID_KEGIATAN_TINGKAT' => 2, 'ID_KEGIATAN_PRESTASI' => 1, 'ID_KEGIATAN_DOKUMEN_TYPE' => 2, 'POINT_KEGIATAN_BOBOT' => 80];
        // Tingkat Regional (ID = 3)
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 2, 'ID_KEGIATAN_TINGKAT' => 3, 'ID_KEGIATAN_PRESTASI' => 1, 'ID_KEGIATAN_DOKUMEN_TYPE' => 2, 'POINT_KEGIATAN_BOBOT' => 60];
        // Tingkat Provinsi (ID = 4)
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 2, 'ID_KEGIATAN_TINGKAT' => 4, 'ID_KEGIATAN_PRESTASI' => 1, 'ID_KEGIATAN_DOKUMEN_TYPE' => 2, 'POINT_KEGIATAN_BOBOT' => 50];
        // Tingkat Kabupaten/Kota (ID = 5)
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 2, 'ID_KEGIATAN_TINGKAT' => 5, 'ID_KEGIATAN_PRESTASI' => 1, 'ID_KEGIATAN_DOKUMEN_TYPE' => 2, 'POINT_KEGIATAN_BOBOT' => 45];
        // Tingkat Universitas (ID = 6)
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 2, 'ID_KEGIATAN_TINGKAT' => 6, 'ID_KEGIATAN_PRESTASI' => 1, 'ID_KEGIATAN_DOKUMEN_TYPE' => 2, 'POINT_KEGIATAN_BOBOT' => 40];
        // Tingkat Fakultas (ID = 7)
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 2, 'ID_KEGIATAN_TINGKAT' => 7, 'ID_KEGIATAN_PRESTASI' => 1, 'ID_KEGIATAN_DOKUMEN_TYPE' => 2, 'POINT_KEGIATAN_BOBOT' => 30];
        // Tingkat Program Studi (ID = 8)
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 2, 'ID_KEGIATAN_TINGKAT' => 8, 'ID_KEGIATAN_PRESTASI' => 1, 'ID_KEGIATAN_DOKUMEN_TYPE' => 2, 'POINT_KEGIATAN_BOBOT' => 25];

        // Juara 2 (ID_KEGIATAN_PRESTASI = 2)
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 2, 'ID_KEGIATAN_TINGKAT' => 1, 'ID_KEGIATAN_PRESTASI' => 2, 'ID_KEGIATAN_DOKUMEN_TYPE' => 2, 'POINT_KEGIATAN_BOBOT' => 90];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 2, 'ID_KEGIATAN_TINGKAT' => 2, 'ID_KEGIATAN_PRESTASI' => 2, 'ID_KEGIATAN_DOKUMEN_TYPE' => 2, 'POINT_KEGIATAN_BOBOT' => 70];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 2, 'ID_KEGIATAN_TINGKAT' => 3, 'ID_KEGIATAN_PRESTASI' => 2, 'ID_KEGIATAN_DOKUMEN_TYPE' => 2, 'POINT_KEGIATAN_BOBOT' => 50];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 2, 'ID_KEGIATAN_TINGKAT' => 4, 'ID_KEGIATAN_PRESTASI' => 2, 'ID_KEGIATAN_DOKUMEN_TYPE' => 2, 'POINT_KEGIATAN_BOBOT' => 45];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 2, 'ID_KEGIATAN_TINGKAT' => 5, 'ID_KEGIATAN_PRESTASI' => 2, 'ID_KEGIATAN_DOKUMEN_TYPE' => 2, 'POINT_KEGIATAN_BOBOT' => 40];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 2, 'ID_KEGIATAN_TINGKAT' => 6, 'ID_KEGIATAN_PRESTASI' => 2, 'ID_KEGIATAN_DOKUMEN_TYPE' => 2, 'POINT_KEGIATAN_BOBOT' => 35];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 2, 'ID_KEGIATAN_TINGKAT' => 7, 'ID_KEGIATAN_PRESTASI' => 2, 'ID_KEGIATAN_DOKUMEN_TYPE' => 2, 'POINT_KEGIATAN_BOBOT' => 25];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 2, 'ID_KEGIATAN_TINGKAT' => 8, 'ID_KEGIATAN_PRESTASI' => 2, 'ID_KEGIATAN_DOKUMEN_TYPE' => 2, 'POINT_KEGIATAN_BOBOT' => 20];

        // Juara 3 (ID_KEGIATAN_PRESTASI = 3)
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 2, 'ID_KEGIATAN_TINGKAT' => 1, 'ID_KEGIATAN_PRESTASI' => 3, 'ID_KEGIATAN_DOKUMEN_TYPE' => 2, 'POINT_KEGIATAN_BOBOT' => 80];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 2, 'ID_KEGIATAN_TINGKAT' => 2, 'ID_KEGIATAN_PRESTASI' => 3, 'ID_KEGIATAN_DOKUMEN_TYPE' => 2, 'POINT_KEGIATAN_BOBOT' => 60];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 2, 'ID_KEGIATAN_TINGKAT' => 3, 'ID_KEGIATAN_PRESTASI' => 3, 'ID_KEGIATAN_DOKUMEN_TYPE' => 2, 'POINT_KEGIATAN_BOBOT' => 45];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 2, 'ID_KEGIATAN_TINGKAT' => 4, 'ID_KEGIATAN_PRESTASI' => 3, 'ID_KEGIATAN_DOKUMEN_TYPE' => 2, 'POINT_KEGIATAN_BOBOT' => 40];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 2, 'ID_KEGIATAN_TINGKAT' => 5, 'ID_KEGIATAN_PRESTASI' => 3, 'ID_KEGIATAN_DOKUMEN_TYPE' => 2, 'POINT_KEGIATAN_BOBOT' => 35];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 2, 'ID_KEGIATAN_TINGKAT' => 6, 'ID_KEGIATAN_PRESTASI' => 3, 'ID_KEGIATAN_DOKUMEN_TYPE' => 2, 'POINT_KEGIATAN_BOBOT' => 30];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 2, 'ID_KEGIATAN_TINGKAT' => 7, 'ID_KEGIATAN_PRESTASI' => 3, 'ID_KEGIATAN_DOKUMEN_TYPE' => 2, 'POINT_KEGIATAN_BOBOT' => 20];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 2, 'ID_KEGIATAN_TINGKAT' => 8, 'ID_KEGIATAN_PRESTASI' => 3, 'ID_KEGIATAN_DOKUMEN_TYPE' => 2, 'POINT_KEGIATAN_BOBOT' => 15];

        // Juara Harapan 1 (ID_KEGIATAN_PRESTASI = 4)
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 2, 'ID_KEGIATAN_TINGKAT' => 1, 'ID_KEGIATAN_PRESTASI' => 4, 'ID_KEGIATAN_DOKUMEN_TYPE' => 2, 'POINT_KEGIATAN_BOBOT' => 70];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 2, 'ID_KEGIATAN_TINGKAT' => 2, 'ID_KEGIATAN_PRESTASI' => 4, 'ID_KEGIATAN_DOKUMEN_TYPE' => 2, 'POINT_KEGIATAN_BOBOT' => 55];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 2, 'ID_KEGIATAN_TINGKAT' => 3, 'ID_KEGIATAN_PRESTASI' => 4, 'ID_KEGIATAN_DOKUMEN_TYPE' => 2, 'POINT_KEGIATAN_BOBOT' => 40];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 2, 'ID_KEGIATAN_TINGKAT' => 4, 'ID_KEGIATAN_PRESTASI' => 4, 'ID_KEGIATAN_DOKUMEN_TYPE' => 2, 'POINT_KEGIATAN_BOBOT' => 35];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 2, 'ID_KEGIATAN_TINGKAT' => 5, 'ID_KEGIATAN_PRESTASI' => 4, 'ID_KEGIATAN_DOKUMEN_TYPE' => 2, 'POINT_KEGIATAN_BOBOT' => 30];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 2, 'ID_KEGIATAN_TINGKAT' => 6, 'ID_KEGIATAN_PRESTASI' => 4, 'ID_KEGIATAN_DOKUMEN_TYPE' => 2, 'POINT_KEGIATAN_BOBOT' => 25];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 2, 'ID_KEGIATAN_TINGKAT' => 7, 'ID_KEGIATAN_PRESTASI' => 4, 'ID_KEGIATAN_DOKUMEN_TYPE' => 2, 'POINT_KEGIATAN_BOBOT' => 18];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 2, 'ID_KEGIATAN_TINGKAT' => 8, 'ID_KEGIATAN_PRESTASI' => 4, 'ID_KEGIATAN_DOKUMEN_TYPE' => 2, 'POINT_KEGIATAN_BOBOT' => 12];

        // Juara Harapan 2 (ID_KEGIATAN_PRESTASI = 5)
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 2, 'ID_KEGIATAN_TINGKAT' => 1, 'ID_KEGIATAN_PRESTASI' => 5, 'ID_KEGIATAN_DOKUMEN_TYPE' => 2, 'POINT_KEGIATAN_BOBOT' => 65];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 2, 'ID_KEGIATAN_TINGKAT' => 2, 'ID_KEGIATAN_PRESTASI' => 5, 'ID_KEGIATAN_DOKUMEN_TYPE' => 2, 'POINT_KEGIATAN_BOBOT' => 50];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 2, 'ID_KEGIATAN_TINGKAT' => 3, 'ID_KEGIATAN_PRESTASI' => 5, 'ID_KEGIATAN_DOKUMEN_TYPE' => 2, 'POINT_KEGIATAN_BOBOT' => 38];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 2, 'ID_KEGIATAN_TINGKAT' => 4, 'ID_KEGIATAN_PRESTASI' => 5, 'ID_KEGIATAN_DOKUMEN_TYPE' => 2, 'POINT_KEGIATAN_BOBOT' => 32];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 2, 'ID_KEGIATAN_TINGKAT' => 5, 'ID_KEGIATAN_PRESTASI' => 5, 'ID_KEGIATAN_DOKUMEN_TYPE' => 2, 'POINT_KEGIATAN_BOBOT' => 28];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 2, 'ID_KEGIATAN_TINGKAT' => 6, 'ID_KEGIATAN_PRESTASI' => 5, 'ID_KEGIATAN_DOKUMEN_TYPE' => 2, 'POINT_KEGIATAN_BOBOT' => 23];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 2, 'ID_KEGIATAN_TINGKAT' => 7, 'ID_KEGIATAN_PRESTASI' => 5, 'ID_KEGIATAN_DOKUMEN_TYPE' => 2, 'POINT_KEGIATAN_BOBOT' => 16];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 2, 'ID_KEGIATAN_TINGKAT' => 8, 'ID_KEGIATAN_PRESTASI' => 5, 'ID_KEGIATAN_DOKUMEN_TYPE' => 2, 'POINT_KEGIATAN_BOBOT' => 10];

        // Juara Harapan 3 (ID_KEGIATAN_PRESTASI = 6)
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 2, 'ID_KEGIATAN_TINGKAT' => 1, 'ID_KEGIATAN_PRESTASI' => 6, 'ID_KEGIATAN_DOKUMEN_TYPE' => 2, 'POINT_KEGIATAN_BOBOT' => 60];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 2, 'ID_KEGIATAN_TINGKAT' => 2, 'ID_KEGIATAN_PRESTASI' => 6, 'ID_KEGIATAN_DOKUMEN_TYPE' => 2, 'POINT_KEGIATAN_BOBOT' => 45];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 2, 'ID_KEGIATAN_TINGKAT' => 3, 'ID_KEGIATAN_PRESTASI' => 6, 'ID_KEGIATAN_DOKUMEN_TYPE' => 2, 'POINT_KEGIATAN_BOBOT' => 35];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 2, 'ID_KEGIATAN_TINGKAT' => 4, 'ID_KEGIATAN_PRESTASI' => 6, 'ID_KEGIATAN_DOKUMEN_TYPE' => 2, 'POINT_KEGIATAN_BOBOT' => 30];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 2, 'ID_KEGIATAN_TINGKAT' => 5, 'ID_KEGIATAN_PRESTASI' => 6, 'ID_KEGIATAN_DOKUMEN_TYPE' => 2, 'POINT_KEGIATAN_BOBOT' => 25];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 2, 'ID_KEGIATAN_TINGKAT' => 6, 'ID_KEGIATAN_PRESTASI' => 6, 'ID_KEGIATAN_DOKUMEN_TYPE' => 2, 'POINT_KEGIATAN_BOBOT' => 20];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 2, 'ID_KEGIATAN_TINGKAT' => 7, 'ID_KEGIATAN_PRESTASI' => 6, 'ID_KEGIATAN_DOKUMEN_TYPE' => 2, 'POINT_KEGIATAN_BOBOT' => 14];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 2, 'ID_KEGIATAN_TINGKAT' => 8, 'ID_KEGIATAN_PRESTASI' => 6, 'ID_KEGIATAN_DOKUMEN_TYPE' => 2, 'POINT_KEGIATAN_BOBOT' => 8];

        // Finalis (ID_KEGIATAN_PRESTASI = 7)
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 2, 'ID_KEGIATAN_TINGKAT' => 1, 'ID_KEGIATAN_PRESTASI' => 7, 'ID_KEGIATAN_DOKUMEN_TYPE' => 1, 'POINT_KEGIATAN_BOBOT' => 55];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 2, 'ID_KEGIATAN_TINGKAT' => 2, 'ID_KEGIATAN_PRESTASI' => 7, 'ID_KEGIATAN_DOKUMEN_TYPE' => 1, 'POINT_KEGIATAN_BOBOT' => 40];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 2, 'ID_KEGIATAN_TINGKAT' => 3, 'ID_KEGIATAN_PRESTASI' => 7, 'ID_KEGIATAN_DOKUMEN_TYPE' => 1, 'POINT_KEGIATAN_BOBOT' => 30];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 2, 'ID_KEGIATAN_TINGKAT' => 4, 'ID_KEGIATAN_PRESTASI' => 7, 'ID_KEGIATAN_DOKUMEN_TYPE' => 1, 'POINT_KEGIATAN_BOBOT' => 25];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 2, 'ID_KEGIATAN_TINGKAT' => 5, 'ID_KEGIATAN_PRESTASI' => 7, 'ID_KEGIATAN_DOKUMEN_TYPE' => 1, 'POINT_KEGIATAN_BOBOT' => 22];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 2, 'ID_KEGIATAN_TINGKAT' => 6, 'ID_KEGIATAN_PRESTASI' => 7, 'ID_KEGIATAN_DOKUMEN_TYPE' => 1, 'POINT_KEGIATAN_BOBOT' => 18];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 2, 'ID_KEGIATAN_TINGKAT' => 7, 'ID_KEGIATAN_PRESTASI' => 7, 'ID_KEGIATAN_DOKUMEN_TYPE' => 1, 'POINT_KEGIATAN_BOBOT' => 12];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 2, 'ID_KEGIATAN_TINGKAT' => 8, 'ID_KEGIATAN_PRESTASI' => 7, 'ID_KEGIATAN_DOKUMEN_TYPE' => 1, 'POINT_KEGIATAN_BOBOT' => 8];

        // Semi Finalis (ID_KEGIATAN_PRESTASI = 8)
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 2, 'ID_KEGIATAN_TINGKAT' => 1, 'ID_KEGIATAN_PRESTASI' => 8, 'ID_KEGIATAN_DOKUMEN_TYPE' => 1, 'POINT_KEGIATAN_BOBOT' => 50];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 2, 'ID_KEGIATAN_TINGKAT' => 2, 'ID_KEGIATAN_PRESTASI' => 8, 'ID_KEGIATAN_DOKUMEN_TYPE' => 1, 'POINT_KEGIATAN_BOBOT' => 35];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 2, 'ID_KEGIATAN_TINGKAT' => 3, 'ID_KEGIATAN_PRESTASI' => 8, 'ID_KEGIATAN_DOKUMEN_TYPE' => 1, 'POINT_KEGIATAN_BOBOT' => 28];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 2, 'ID_KEGIATAN_TINGKAT' => 4, 'ID_KEGIATAN_PRESTASI' => 8, 'ID_KEGIATAN_DOKUMEN_TYPE' => 1, 'POINT_KEGIATAN_BOBOT' => 23];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 2, 'ID_KEGIATAN_TINGKAT' => 5, 'ID_KEGIATAN_PRESTASI' => 8, 'ID_KEGIATAN_DOKUMEN_TYPE' => 1, 'POINT_KEGIATAN_BOBOT' => 20];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 2, 'ID_KEGIATAN_TINGKAT' => 6, 'ID_KEGIATAN_PRESTASI' => 8, 'ID_KEGIATAN_DOKUMEN_TYPE' => 1, 'POINT_KEGIATAN_BOBOT' => 15];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 2, 'ID_KEGIATAN_TINGKAT' => 7, 'ID_KEGIATAN_PRESTASI' => 8, 'ID_KEGIATAN_DOKUMEN_TYPE' => 1, 'POINT_KEGIATAN_BOBOT' => 10];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 2, 'ID_KEGIATAN_TINGKAT' => 8, 'ID_KEGIATAN_PRESTASI' => 8, 'ID_KEGIATAN_DOKUMEN_TYPE' => 1, 'POINT_KEGIATAN_BOBOT' => 6];

        // Peserta (ID_KEGIATAN_PRESTASI = 9)
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 2, 'ID_KEGIATAN_TINGKAT' => 1, 'ID_KEGIATAN_PRESTASI' => 9, 'ID_KEGIATAN_DOKUMEN_TYPE' => 1, 'POINT_KEGIATAN_BOBOT' => 45];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 2, 'ID_KEGIATAN_TINGKAT' => 2, 'ID_KEGIATAN_PRESTASI' => 9, 'ID_KEGIATAN_DOKUMEN_TYPE' => 1, 'POINT_KEGIATAN_BOBOT' => 30];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 2, 'ID_KEGIATAN_TINGKAT' => 3, 'ID_KEGIATAN_PRESTASI' => 9, 'ID_KEGIATAN_DOKUMEN_TYPE' => 1, 'POINT_KEGIATAN_BOBOT' => 25];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 2, 'ID_KEGIATAN_TINGKAT' => 4, 'ID_KEGIATAN_PRESTASI' => 9, 'ID_KEGIATAN_DOKUMEN_TYPE' => 1, 'POINT_KEGIATAN_BOBOT' => 20];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 2, 'ID_KEGIATAN_TINGKAT' => 5, 'ID_KEGIATAN_PRESTASI' => 9, 'ID_KEGIATAN_DOKUMEN_TYPE' => 1, 'POINT_KEGIATAN_BOBOT' => 18];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 2, 'ID_KEGIATAN_TINGKAT' => 6, 'ID_KEGIATAN_PRESTASI' => 9, 'ID_KEGIATAN_DOKUMEN_TYPE' => 1, 'POINT_KEGIATAN_BOBOT' => 12];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 2, 'ID_KEGIATAN_TINGKAT' => 7, 'ID_KEGIATAN_PRESTASI' => 9, 'ID_KEGIATAN_DOKUMEN_TYPE' => 1, 'POINT_KEGIATAN_BOBOT' => 8];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 2, 'ID_KEGIATAN_TINGKAT' => 8, 'ID_KEGIATAN_PRESTASI' => 9, 'ID_KEGIATAN_DOKUMEN_TYPE' => 1, 'POINT_KEGIATAN_BOBOT' => 5];

        // Pembicara/Narasumber (ID_KEGIATAN_PRESTASI = 10)
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 2, 'ID_KEGIATAN_TINGKAT' => 1, 'ID_KEGIATAN_PRESTASI' => 10, 'ID_KEGIATAN_DOKUMEN_TYPE' => 1, 'POINT_KEGIATAN_BOBOT' => 50];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 2, 'ID_KEGIATAN_TINGKAT' => 2, 'ID_KEGIATAN_PRESTASI' => 10, 'ID_KEGIATAN_DOKUMEN_TYPE' => 1, 'POINT_KEGIATAN_BOBOT' => 35];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 2, 'ID_KEGIATAN_TINGKAT' => 3, 'ID_KEGIATAN_PRESTASI' => 10, 'ID_KEGIATAN_DOKUMEN_TYPE' => 1, 'POINT_KEGIATAN_BOBOT' => 28];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 2, 'ID_KEGIATAN_TINGKAT' => 4, 'ID_KEGIATAN_PRESTASI' => 10, 'ID_KEGIATAN_DOKUMEN_TYPE' => 1, 'POINT_KEGIATAN_BOBOT' => 23];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 2, 'ID_KEGIATAN_TINGKAT' => 5, 'ID_KEGIATAN_PRESTASI' => 10, 'ID_KEGIATAN_DOKUMEN_TYPE' => 1, 'POINT_KEGIATAN_BOBOT' => 20];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 2, 'ID_KEGIATAN_TINGKAT' => 6, 'ID_KEGIATAN_PRESTASI' => 10, 'ID_KEGIATAN_DOKUMEN_TYPE' => 1, 'POINT_KEGIATAN_BOBOT' => 15];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 2, 'ID_KEGIATAN_TINGKAT' => 7, 'ID_KEGIATAN_PRESTASI' => 10, 'ID_KEGIATAN_DOKUMEN_TYPE' => 1, 'POINT_KEGIATAN_BOBOT' => 10];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 2, 'ID_KEGIATAN_TINGKAT' => 8, 'ID_KEGIATAN_PRESTASI' => 10, 'ID_KEGIATAN_DOKUMEN_TYPE' => 1, 'POINT_KEGIATAN_BOBOT' => 6];

        // Panitia (ID_KEGIATAN_PRESTASI = 11)
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 2, 'ID_KEGIATAN_TINGKAT' => 1, 'ID_KEGIATAN_PRESTASI' => 11, 'ID_KEGIATAN_DOKUMEN_TYPE' => 3, 'POINT_KEGIATAN_BOBOT' => 40];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 2, 'ID_KEGIATAN_TINGKAT' => 2, 'ID_KEGIATAN_PRESTASI' => 11, 'ID_KEGIATAN_DOKUMEN_TYPE' => 3, 'POINT_KEGIATAN_BOBOT' => 25];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 2, 'ID_KEGIATAN_TINGKAT' => 3, 'ID_KEGIATAN_PRESTASI' => 11, 'ID_KEGIATAN_DOKUMEN_TYPE' => 3, 'POINT_KEGIATAN_BOBOT' => 20];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 2, 'ID_KEGIATAN_TINGKAT' => 4, 'ID_KEGIATAN_PRESTASI' => 11, 'ID_KEGIATAN_DOKUMEN_TYPE' => 3, 'POINT_KEGIATAN_BOBOT' => 18];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 2, 'ID_KEGIATAN_TINGKAT' => 5, 'ID_KEGIATAN_PRESTASI' => 11, 'ID_KEGIATAN_DOKUMEN_TYPE' => 3, 'POINT_KEGIATAN_BOBOT' => 15];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 2, 'ID_KEGIATAN_TINGKAT' => 6, 'ID_KEGIATAN_PRESTASI' => 11, 'ID_KEGIATAN_DOKUMEN_TYPE' => 3, 'POINT_KEGIATAN_BOBOT' => 10];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 2, 'ID_KEGIATAN_TINGKAT' => 7, 'ID_KEGIATAN_PRESTASI' => 11, 'ID_KEGIATAN_DOKUMEN_TYPE' => 3, 'POINT_KEGIATAN_BOBOT' => 7];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 2, 'ID_KEGIATAN_TINGKAT' => 8, 'ID_KEGIATAN_PRESTASI' => 11, 'ID_KEGIATAN_DOKUMEN_TYPE' => 3, 'POINT_KEGIATAN_BOBOT' => 5];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 2, 'ID_KEGIATAN_TINGKAT' => 8, 'ID_KEGIATAN_PRESTASI' => 11, 'ID_KEGIATAN_DOKUMEN_TYPE' => 3, 'POINT_KEGIATAN_BOBOT' => 5];

        // ===== KEGIATAN PILIHAN: MINAT, BAKAT DAN KEROHANIAN (ID_KEGIATAN_JENIS = 3, IS_HAVE_TINGKAT = true) =====

        // Juara 1 (ID_KEGIATAN_PRESTASI = 1)
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 3, 'ID_KEGIATAN_TINGKAT' => 1, 'ID_KEGIATAN_PRESTASI' => 1, 'ID_KEGIATAN_DOKUMEN_TYPE' => 2, 'POINT_KEGIATAN_BOBOT' => 100];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 3, 'ID_KEGIATAN_TINGKAT' => 2, 'ID_KEGIATAN_PRESTASI' => 1, 'ID_KEGIATAN_DOKUMEN_TYPE' => 2, 'POINT_KEGIATAN_BOBOT' => 80];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 3, 'ID_KEGIATAN_TINGKAT' => 3, 'ID_KEGIATAN_PRESTASI' => 1, 'ID_KEGIATAN_DOKUMEN_TYPE' => 2, 'POINT_KEGIATAN_BOBOT' => 60];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 3, 'ID_KEGIATAN_TINGKAT' => 4, 'ID_KEGIATAN_PRESTASI' => 1, 'ID_KEGIATAN_DOKUMEN_TYPE' => 2, 'POINT_KEGIATAN_BOBOT' => 50];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 3, 'ID_KEGIATAN_TINGKAT' => 5, 'ID_KEGIATAN_PRESTASI' => 1, 'ID_KEGIATAN_DOKUMEN_TYPE' => 2, 'POINT_KEGIATAN_BOBOT' => 45];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 3, 'ID_KEGIATAN_TINGKAT' => 6, 'ID_KEGIATAN_PRESTASI' => 1, 'ID_KEGIATAN_DOKUMEN_TYPE' => 2, 'POINT_KEGIATAN_BOBOT' => 40];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 3, 'ID_KEGIATAN_TINGKAT' => 7, 'ID_KEGIATAN_PRESTASI' => 1, 'ID_KEGIATAN_DOKUMEN_TYPE' => 2, 'POINT_KEGIATAN_BOBOT' => 30];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 3, 'ID_KEGIATAN_TINGKAT' => 8, 'ID_KEGIATAN_PRESTASI' => 1, 'ID_KEGIATAN_DOKUMEN_TYPE' => 2, 'POINT_KEGIATAN_BOBOT' => 25];

        // Juara 2 (ID_KEGIATAN_PRESTASI = 2)
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 3, 'ID_KEGIATAN_TINGKAT' => 1, 'ID_KEGIATAN_PRESTASI' => 2, 'ID_KEGIATAN_DOKUMEN_TYPE' => 2, 'POINT_KEGIATAN_BOBOT' => 90];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 3, 'ID_KEGIATAN_TINGKAT' => 2, 'ID_KEGIATAN_PRESTASI' => 2, 'ID_KEGIATAN_DOKUMEN_TYPE' => 2, 'POINT_KEGIATAN_BOBOT' => 70];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 3, 'ID_KEGIATAN_TINGKAT' => 3, 'ID_KEGIATAN_PRESTASI' => 2, 'ID_KEGIATAN_DOKUMEN_TYPE' => 2, 'POINT_KEGIATAN_BOBOT' => 50];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 3, 'ID_KEGIATAN_TINGKAT' => 4, 'ID_KEGIATAN_PRESTASI' => 2, 'ID_KEGIATAN_DOKUMEN_TYPE' => 2, 'POINT_KEGIATAN_BOBOT' => 45];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 3, 'ID_KEGIATAN_TINGKAT' => 5, 'ID_KEGIATAN_PRESTASI' => 2, 'ID_KEGIATAN_DOKUMEN_TYPE' => 2, 'POINT_KEGIATAN_BOBOT' => 40];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 3, 'ID_KEGIATAN_TINGKAT' => 6, 'ID_KEGIATAN_PRESTASI' => 2, 'ID_KEGIATAN_DOKUMEN_TYPE' => 2, 'POINT_KEGIATAN_BOBOT' => 35];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 3, 'ID_KEGIATAN_TINGKAT' => 7, 'ID_KEGIATAN_PRESTASI' => 2, 'ID_KEGIATAN_DOKUMEN_TYPE' => 2, 'POINT_KEGIATAN_BOBOT' => 25];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 3, 'ID_KEGIATAN_TINGKAT' => 8, 'ID_KEGIATAN_PRESTASI' => 2, 'ID_KEGIATAN_DOKUMEN_TYPE' => 2, 'POINT_KEGIATAN_BOBOT' => 20];

        // Juara 3 (ID_KEGIATAN_PRESTASI = 3)
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 3, 'ID_KEGIATAN_TINGKAT' => 1, 'ID_KEGIATAN_PRESTASI' => 3, 'ID_KEGIATAN_DOKUMEN_TYPE' => 2, 'POINT_KEGIATAN_BOBOT' => 80];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 3, 'ID_KEGIATAN_TINGKAT' => 2, 'ID_KEGIATAN_PRESTASI' => 3, 'ID_KEGIATAN_DOKUMEN_TYPE' => 2, 'POINT_KEGIATAN_BOBOT' => 60];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 3, 'ID_KEGIATAN_TINGKAT' => 3, 'ID_KEGIATAN_PRESTASI' => 3, 'ID_KEGIATAN_DOKUMEN_TYPE' => 2, 'POINT_KEGIATAN_BOBOT' => 45];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 3, 'ID_KEGIATAN_TINGKAT' => 4, 'ID_KEGIATAN_PRESTASI' => 3, 'ID_KEGIATAN_DOKUMEN_TYPE' => 2, 'POINT_KEGIATAN_BOBOT' => 40];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 3, 'ID_KEGIATAN_TINGKAT' => 5, 'ID_KEGIATAN_PRESTASI' => 3, 'ID_KEGIATAN_DOKUMEN_TYPE' => 2, 'POINT_KEGIATAN_BOBOT' => 35];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 3, 'ID_KEGIATAN_TINGKAT' => 6, 'ID_KEGIATAN_PRESTASI' => 3, 'ID_KEGIATAN_DOKUMEN_TYPE' => 2, 'POINT_KEGIATAN_BOBOT' => 30];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 3, 'ID_KEGIATAN_TINGKAT' => 7, 'ID_KEGIATAN_PRESTASI' => 3, 'ID_KEGIATAN_DOKUMEN_TYPE' => 2, 'POINT_KEGIATAN_BOBOT' => 20];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 3, 'ID_KEGIATAN_TINGKAT' => 8, 'ID_KEGIATAN_PRESTASI' => 3, 'ID_KEGIATAN_DOKUMEN_TYPE' => 2, 'POINT_KEGIATAN_BOBOT' => 15];

        // Juara Harapan 1 (ID_KEGIATAN_PRESTASI = 4)
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 3, 'ID_KEGIATAN_TINGKAT' => 1, 'ID_KEGIATAN_PRESTASI' => 4, 'ID_KEGIATAN_DOKUMEN_TYPE' => 2, 'POINT_KEGIATAN_BOBOT' => 70];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 3, 'ID_KEGIATAN_TINGKAT' => 2, 'ID_KEGIATAN_PRESTASI' => 4, 'ID_KEGIATAN_DOKUMEN_TYPE' => 2, 'POINT_KEGIATAN_BOBOT' => 55];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 3, 'ID_KEGIATAN_TINGKAT' => 3, 'ID_KEGIATAN_PRESTASI' => 4, 'ID_KEGIATAN_DOKUMEN_TYPE' => 2, 'POINT_KEGIATAN_BOBOT' => 40];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 3, 'ID_KEGIATAN_TINGKAT' => 4, 'ID_KEGIATAN_PRESTASI' => 4, 'ID_KEGIATAN_DOKUMEN_TYPE' => 2, 'POINT_KEGIATAN_BOBOT' => 35];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 3, 'ID_KEGIATAN_TINGKAT' => 5, 'ID_KEGIATAN_PRESTASI' => 4, 'ID_KEGIATAN_DOKUMEN_TYPE' => 2, 'POINT_KEGIATAN_BOBOT' => 30];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 3, 'ID_KEGIATAN_TINGKAT' => 6, 'ID_KEGIATAN_PRESTASI' => 4, 'ID_KEGIATAN_DOKUMEN_TYPE' => 2, 'POINT_KEGIATAN_BOBOT' => 25];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 3, 'ID_KEGIATAN_TINGKAT' => 7, 'ID_KEGIATAN_PRESTASI' => 4, 'ID_KEGIATAN_DOKUMEN_TYPE' => 2, 'POINT_KEGIATAN_BOBOT' => 18];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 3, 'ID_KEGIATAN_TINGKAT' => 8, 'ID_KEGIATAN_PRESTASI' => 4, 'ID_KEGIATAN_DOKUMEN_TYPE' => 2, 'POINT_KEGIATAN_BOBOT' => 12];

        // Juara Harapan 2 (ID_KEGIATAN_PRESTASI = 5)
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 3, 'ID_KEGIATAN_TINGKAT' => 1, 'ID_KEGIATAN_PRESTASI' => 5, 'ID_KEGIATAN_DOKUMEN_TYPE' => 2, 'POINT_KEGIATAN_BOBOT' => 65];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 3, 'ID_KEGIATAN_TINGKAT' => 2, 'ID_KEGIATAN_PRESTASI' => 5, 'ID_KEGIATAN_DOKUMEN_TYPE' => 2, 'POINT_KEGIATAN_BOBOT' => 50];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 3, 'ID_KEGIATAN_TINGKAT' => 3, 'ID_KEGIATAN_PRESTASI' => 5, 'ID_KEGIATAN_DOKUMEN_TYPE' => 2, 'POINT_KEGIATAN_BOBOT' => 38];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 3, 'ID_KEGIATAN_TINGKAT' => 4, 'ID_KEGIATAN_PRESTASI' => 5, 'ID_KEGIATAN_DOKUMEN_TYPE' => 2, 'POINT_KEGIATAN_BOBOT' => 32];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 3, 'ID_KEGIATAN_TINGKAT' => 5, 'ID_KEGIATAN_PRESTASI' => 5, 'ID_KEGIATAN_DOKUMEN_TYPE' => 2, 'POINT_KEGIATAN_BOBOT' => 28];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 3, 'ID_KEGIATAN_TINGKAT' => 6, 'ID_KEGIATAN_PRESTASI' => 5, 'ID_KEGIATAN_DOKUMEN_TYPE' => 2, 'POINT_KEGIATAN_BOBOT' => 23];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 3, 'ID_KEGIATAN_TINGKAT' => 7, 'ID_KEGIATAN_PRESTASI' => 5, 'ID_KEGIATAN_DOKUMEN_TYPE' => 2, 'POINT_KEGIATAN_BOBOT' => 16];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 3, 'ID_KEGIATAN_TINGKAT' => 8, 'ID_KEGIATAN_PRESTASI' => 5, 'ID_KEGIATAN_DOKUMEN_TYPE' => 2, 'POINT_KEGIATAN_BOBOT' => 10];

        // Juara Harapan 3 (ID_KEGIATAN_PRESTASI = 6)
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 3, 'ID_KEGIATAN_TINGKAT' => 1, 'ID_KEGIATAN_PRESTASI' => 6, 'ID_KEGIATAN_DOKUMEN_TYPE' => 2, 'POINT_KEGIATAN_BOBOT' => 60];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 3, 'ID_KEGIATAN_TINGKAT' => 2, 'ID_KEGIATAN_PRESTASI' => 6, 'ID_KEGIATAN_DOKUMEN_TYPE' => 2, 'POINT_KEGIATAN_BOBOT' => 45];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 3, 'ID_KEGIATAN_TINGKAT' => 3, 'ID_KEGIATAN_PRESTASI' => 6, 'ID_KEGIATAN_DOKUMEN_TYPE' => 2, 'POINT_KEGIATAN_BOBOT' => 35];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 3, 'ID_KEGIATAN_TINGKAT' => 4, 'ID_KEGIATAN_PRESTASI' => 6, 'ID_KEGIATAN_DOKUMEN_TYPE' => 2, 'POINT_KEGIATAN_BOBOT' => 30];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 3, 'ID_KEGIATAN_TINGKAT' => 5, 'ID_KEGIATAN_PRESTASI' => 6, 'ID_KEGIATAN_DOKUMEN_TYPE' => 2, 'POINT_KEGIATAN_BOBOT' => 25];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 3, 'ID_KEGIATAN_TINGKAT' => 6, 'ID_KEGIATAN_PRESTASI' => 6, 'ID_KEGIATAN_DOKUMEN_TYPE' => 2, 'POINT_KEGIATAN_BOBOT' => 20];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 3, 'ID_KEGIATAN_TINGKAT' => 7, 'ID_KEGIATAN_PRESTASI' => 6, 'ID_KEGIATAN_DOKUMEN_TYPE' => 2, 'POINT_KEGIATAN_BOBOT' => 14];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 3, 'ID_KEGIATAN_TINGKAT' => 8, 'ID_KEGIATAN_PRESTASI' => 6, 'ID_KEGIATAN_DOKUMEN_TYPE' => 2, 'POINT_KEGIATAN_BOBOT' => 8];

        // Finalis (ID_KEGIATAN_PRESTASI = 7)
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 3, 'ID_KEGIATAN_TINGKAT' => 1, 'ID_KEGIATAN_PRESTASI' => 7, 'ID_KEGIATAN_DOKUMEN_TYPE' => 1, 'POINT_KEGIATAN_BOBOT' => 55];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 3, 'ID_KEGIATAN_TINGKAT' => 2, 'ID_KEGIATAN_PRESTASI' => 7, 'ID_KEGIATAN_DOKUMEN_TYPE' => 1, 'POINT_KEGIATAN_BOBOT' => 40];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 3, 'ID_KEGIATAN_TINGKAT' => 3, 'ID_KEGIATAN_PRESTASI' => 7, 'ID_KEGIATAN_DOKUMEN_TYPE' => 1, 'POINT_KEGIATAN_BOBOT' => 30];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 3, 'ID_KEGIATAN_TINGKAT' => 4, 'ID_KEGIATAN_PRESTASI' => 7, 'ID_KEGIATAN_DOKUMEN_TYPE' => 1, 'POINT_KEGIATAN_BOBOT' => 25];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 3, 'ID_KEGIATAN_TINGKAT' => 5, 'ID_KEGIATAN_PRESTASI' => 7, 'ID_KEGIATAN_DOKUMEN_TYPE' => 1, 'POINT_KEGIATAN_BOBOT' => 22];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 3, 'ID_KEGIATAN_TINGKAT' => 6, 'ID_KEGIATAN_PRESTASI' => 7, 'ID_KEGIATAN_DOKUMEN_TYPE' => 1, 'POINT_KEGIATAN_BOBOT' => 18];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 3, 'ID_KEGIATAN_TINGKAT' => 7, 'ID_KEGIATAN_PRESTASI' => 7, 'ID_KEGIATAN_DOKUMEN_TYPE' => 1, 'POINT_KEGIATAN_BOBOT' => 12];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 3, 'ID_KEGIATAN_TINGKAT' => 8, 'ID_KEGIATAN_PRESTASI' => 7, 'ID_KEGIATAN_DOKUMEN_TYPE' => 1, 'POINT_KEGIATAN_BOBOT' => 8];

        // Semi Finalis (ID_KEGIATAN_PRESTASI = 8)
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 3, 'ID_KEGIATAN_TINGKAT' => 1, 'ID_KEGIATAN_PRESTASI' => 8, 'ID_KEGIATAN_DOKUMEN_TYPE' => 1, 'POINT_KEGIATAN_BOBOT' => 50];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 3, 'ID_KEGIATAN_TINGKAT' => 2, 'ID_KEGIATAN_PRESTASI' => 8, 'ID_KEGIATAN_DOKUMEN_TYPE' => 1, 'POINT_KEGIATAN_BOBOT' => 35];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 3, 'ID_KEGIATAN_TINGKAT' => 3, 'ID_KEGIATAN_PRESTASI' => 8, 'ID_KEGIATAN_DOKUMEN_TYPE' => 1, 'POINT_KEGIATAN_BOBOT' => 28];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 3, 'ID_KEGIATAN_TINGKAT' => 4, 'ID_KEGIATAN_PRESTASI' => 8, 'ID_KEGIATAN_DOKUMEN_TYPE' => 1, 'POINT_KEGIATAN_BOBOT' => 23];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 3, 'ID_KEGIATAN_TINGKAT' => 5, 'ID_KEGIATAN_PRESTASI' => 8, 'ID_KEGIATAN_DOKUMEN_TYPE' => 1, 'POINT_KEGIATAN_BOBOT' => 20];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 3, 'ID_KEGIATAN_TINGKAT' => 6, 'ID_KEGIATAN_PRESTASI' => 8, 'ID_KEGIATAN_DOKUMEN_TYPE' => 1, 'POINT_KEGIATAN_BOBOT' => 15];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 3, 'ID_KEGIATAN_TINGKAT' => 7, 'ID_KEGIATAN_PRESTASI' => 8, 'ID_KEGIATAN_DOKUMEN_TYPE' => 1, 'POINT_KEGIATAN_BOBOT' => 10];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 3, 'ID_KEGIATAN_TINGKAT' => 8, 'ID_KEGIATAN_PRESTASI' => 8, 'ID_KEGIATAN_DOKUMEN_TYPE' => 1, 'POINT_KEGIATAN_BOBOT' => 6];

        // Peserta (ID_KEGIATAN_PRESTASI = 9)
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 3, 'ID_KEGIATAN_TINGKAT' => 1, 'ID_KEGIATAN_PRESTASI' => 9, 'ID_KEGIATAN_DOKUMEN_TYPE' => 1, 'POINT_KEGIATAN_BOBOT' => 45];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 3, 'ID_KEGIATAN_TINGKAT' => 2, 'ID_KEGIATAN_PRESTASI' => 9, 'ID_KEGIATAN_DOKUMEN_TYPE' => 1, 'POINT_KEGIATAN_BOBOT' => 30];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 3, 'ID_KEGIATAN_TINGKAT' => 3, 'ID_KEGIATAN_PRESTASI' => 9, 'ID_KEGIATAN_DOKUMEN_TYPE' => 1, 'POINT_KEGIATAN_BOBOT' => 25];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 3, 'ID_KEGIATAN_TINGKAT' => 4, 'ID_KEGIATAN_PRESTASI' => 9, 'ID_KEGIATAN_DOKUMEN_TYPE' => 1, 'POINT_KEGIATAN_BOBOT' => 20];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 3, 'ID_KEGIATAN_TINGKAT' => 5, 'ID_KEGIATAN_PRESTASI' => 9, 'ID_KEGIATAN_DOKUMEN_TYPE' => 1, 'POINT_KEGIATAN_BOBOT' => 18];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 3, 'ID_KEGIATAN_TINGKAT' => 6, 'ID_KEGIATAN_PRESTASI' => 9, 'ID_KEGIATAN_DOKUMEN_TYPE' => 1, 'POINT_KEGIATAN_BOBOT' => 12];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 3, 'ID_KEGIATAN_TINGKAT' => 7, 'ID_KEGIATAN_PRESTASI' => 9, 'ID_KEGIATAN_DOKUMEN_TYPE' => 1, 'POINT_KEGIATAN_BOBOT' => 8];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 3, 'ID_KEGIATAN_TINGKAT' => 8, 'ID_KEGIATAN_PRESTASI' => 9, 'ID_KEGIATAN_DOKUMEN_TYPE' => 1, 'POINT_KEGIATAN_BOBOT' => 5];

        // Pembicara/Narasumber (ID_KEGIATAN_PRESTASI = 10)
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 3, 'ID_KEGIATAN_TINGKAT' => 1, 'ID_KEGIATAN_PRESTASI' => 10, 'ID_KEGIATAN_DOKUMEN_TYPE' => 1, 'POINT_KEGIATAN_BOBOT' => 50];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 3, 'ID_KEGIATAN_TINGKAT' => 2, 'ID_KEGIATAN_PRESTASI' => 10, 'ID_KEGIATAN_DOKUMEN_TYPE' => 1, 'POINT_KEGIATAN_BOBOT' => 35];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 3, 'ID_KEGIATAN_TINGKAT' => 3, 'ID_KEGIATAN_PRESTASI' => 10, 'ID_KEGIATAN_DOKUMEN_TYPE' => 1, 'POINT_KEGIATAN_BOBOT' => 28];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 3, 'ID_KEGIATAN_TINGKAT' => 4, 'ID_KEGIATAN_PRESTASI' => 10, 'ID_KEGIATAN_DOKUMEN_TYPE' => 1, 'POINT_KEGIATAN_BOBOT' => 23];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 3, 'ID_KEGIATAN_TINGKAT' => 5, 'ID_KEGIATAN_PRESTASI' => 10, 'ID_KEGIATAN_DOKUMEN_TYPE' => 1, 'POINT_KEGIATAN_BOBOT' => 20];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 3, 'ID_KEGIATAN_TINGKAT' => 6, 'ID_KEGIATAN_PRESTASI' => 10, 'ID_KEGIATAN_DOKUMEN_TYPE' => 1, 'POINT_KEGIATAN_BOBOT' => 15];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 3, 'ID_KEGIATAN_TINGKAT' => 7, 'ID_KEGIATAN_PRESTASI' => 10, 'ID_KEGIATAN_DOKUMEN_TYPE' => 1, 'POINT_KEGIATAN_BOBOT' => 10];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 3, 'ID_KEGIATAN_TINGKAT' => 8, 'ID_KEGIATAN_PRESTASI' => 10, 'ID_KEGIATAN_DOKUMEN_TYPE' => 1, 'POINT_KEGIATAN_BOBOT' => 6];

        // Panitia (ID_KEGIATAN_PRESTASI = 11)
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 3, 'ID_KEGIATAN_TINGKAT' => 1, 'ID_KEGIATAN_PRESTASI' => 11, 'ID_KEGIATAN_DOKUMEN_TYPE' => 3, 'POINT_KEGIATAN_BOBOT' => 40];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 3, 'ID_KEGIATAN_TINGKAT' => 2, 'ID_KEGIATAN_PRESTASI' => 11, 'ID_KEGIATAN_DOKUMEN_TYPE' => 3, 'POINT_KEGIATAN_BOBOT' => 25];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 3, 'ID_KEGIATAN_TINGKAT' => 3, 'ID_KEGIATAN_PRESTASI' => 11, 'ID_KEGIATAN_DOKUMEN_TYPE' => 3, 'POINT_KEGIATAN_BOBOT' => 20];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 3, 'ID_KEGIATAN_TINGKAT' => 4, 'ID_KEGIATAN_PRESTASI' => 11, 'ID_KEGIATAN_DOKUMEN_TYPE' => 3, 'POINT_KEGIATAN_BOBOT' => 18];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 3, 'ID_KEGIATAN_TINGKAT' => 5, 'ID_KEGIATAN_PRESTASI' => 11, 'ID_KEGIATAN_DOKUMEN_TYPE' => 3, 'POINT_KEGIATAN_BOBOT' => 15];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 3, 'ID_KEGIATAN_TINGKAT' => 6, 'ID_KEGIATAN_PRESTASI' => 11, 'ID_KEGIATAN_DOKUMEN_TYPE' => 3, 'POINT_KEGIATAN_BOBOT' => 10];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 3, 'ID_KEGIATAN_TINGKAT' => 7, 'ID_KEGIATAN_PRESTASI' => 11, 'ID_KEGIATAN_DOKUMEN_TYPE' => 3, 'POINT_KEGIATAN_BOBOT' => 7];
        $bobotData[] = ['ID_KEGIATAN_JENIS' => 3, 'ID_KEGIATAN_TINGKAT' => 8, 'ID_KEGIATAN_PRESTASI' => 11, 'ID_KEGIATAN_DOKUMEN_TYPE' => 3, 'POINT_KEGIATAN_BOBOT' => 5];

        DB::table('KEGIATAN_BOBOT')->insert($bobotData);
    }
}
