services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sistem-langitan-v2
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - /root/sistem-langitan-v2/storage/logs:/var/www/html/storage/logs
      - /root/sistem-langitan-v2/storage/app:/var/www/html/storage/app
