ALTER TABLE UMAHA.PRESENSI_KELAS ADD QR_KEY VARCHAR2(200) NULL;
COMMENT ON COLUMN UMAHA.PRESENSI_KELAS.QR_KEY IS 'KEY UNTUK VALIDASI QR';
ALTER TABLE UMAHA.PRESENSI_KELAS ADD QR_EXPIRED DATE NULL;
COMMENT ON COLUMN UMAHA.PRESENSI_KELAS.QR_EXPIRED IS 'UNTUK VALIDASI TIME EXPIRED QR';
