name: CI/CD on Pull Request to Develop

on:
  pull_request:
    types: [closed]
    branches:
      - develop # Target branch untuk PR

jobs:
  # Job ini hanya akan berjalan jika PR berhasil di-merge
  deploy:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 2246 # Opsional: jika menggunakan port khusus
          script: |
            # Ganti dengan path direktori proyek Anda di server
            cd /var/www/sistem-langitan-v2

            # Update kode dari git
            git pull origin develop # Pastikan pull dari branch develop

            echo "Deployment berhasil!"
