name: Auto Merge PR And Deploy

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - develop

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Enable Auto-merge
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ github.event.number }}
          merge-method: merge
          
      - name: Add Comment
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🤖 **Auto-merge enabled!** This PR will be merged automatically when all requirements are met.'
            });
            
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 2246
          script: |
            # Ganti dengan path direktori proyek Anda di server
            cd /var/www/sistem-langitan-v2
            
            # Update kode dari git
            git pull origin develop
            
            echo "Deployment berhasil!"
            
      - name: Add Comment Deploy
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'This PR deployed to Server'
            });
            
            
